apiVersion: v1
kind: Service
metadata:
  name: sidecar
spec:
  selector:
    app: sidecar
  ports:
  - protocol: "TCP"
    port: 50051
    targetPort: 50051
  type: LoadBalancer

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sidecar
spec:
  selector:
    matchLabels:
      app: sidecar
  replicas: 1
  template:
    metadata:
      labels:
        app: sidecar
    spec:
      containers:
      - name: sidecar
        image: sidecar:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 50051