apiVersion: apps/v1
kind: Deployment
metadata:
  name: sidecar-python
spec:
  selector:
    matchLabels:
      app: sidecar-python
  replicas: 1
  template:
    metadata:
      labels:
        app: sidecar-python
    spec:
      containers:
      - name: sidecar-python
        image: sidecar_python:latest
        imagePullPolicy: IfNotPresent
        envFrom:
          - secretRef:
              name: sidecar-secrets

      - name: main-application
        image: main_application:latest
        imagePullPolicy: IfNotPresent
        envFrom:
          - secretRef:
               name: sidecar-secrets