apiVersion: apps/v1
kind: Deployment
metadata:
  name: sidecar
spec:
  selector:
    matchLabels:
      app: sidecar
  replicas: 1
  template:
    metadata:
      labels:
        app: sidecar
    spec:
      containers:
      - name: sidecar
        image: sidecar:latest
        imagePullPolicy: Never
        envFrom:
          - secretRef:
              name: sidecar-secrets
        ports:
          - containerPort: 50051

      - name: main-application
        image: main_application:latest
        imagePullPolicy: Never
        envFrom:
          - secretRef:
               name: sidecar-secrets
        ports:
          - containerPort: 50051